#FROM nvcr.io/nvidia/rapidsai/rapidsai-core:23.02-cuda11.5-runtime-ubuntu20.04-py3.10
FROM rapidsai/rapidsai-core:23.02-cuda11.5-runtime-ubuntu20.04-py3.10

RUN apt-get update && apt-get install -y --no-install-recommends

RUN apt-get install -y wget build-essential libssl-dev

# added in v0.61
RUN pip install jupyterlab-git

# added in v0.62
RUN apt-get install htop

# added in v0.63
RUN apt-get install nano

# added in v0.64
RUN pip install seaborn

# added in v0.65
RUN pip install cookiecutter

# added in v0.66
RUN pip install xlrd
RUN pip install openpyxl

# added in v0.67
RUN pip install wandb

# added in v0.68
RUN pip install statsmodels
RUN pip install protobuf==3.20.1

# added in v0.69
RUN pip install ipywidgets
RUN apt-get install -y zip

# added in v0.80
RUN pip install networkx
